### ISSUE TITLE
build error,missing libs

### ISSUE THREAD

**Issue by jmp0x7c00** [yang-sec/PrivacyGuard#6]
Hi,dear
some errors occurred when building PrivacyGuard:

https://github.com/yang-sec/PrivacyGuard/blob/1ef665fca9dadf00bc0bb363842ab471a747ab0a/CEE/Makefile#L99
https://github.com/yang-sec/PrivacyGuard/blob/1ef665fca9dadf00bc0bb363842ab471a747ab0a/CEE/Makefile#L100
log:
```
CXX  <=  service_provider/ecp.cpp
CXX  <=  service_provider/network_ra.cpp
CXX  <=  service_provider/service_provider.cpp
CXX  <=  service_provider/ias_ra.cpp
LINK =>  libservice_provider.so
GEN  =>  isv_app/isv_enclave_u.c
CC   <=  isv_app/isv_enclave_u.c
CXX  <=  isv_app/isv_app.cpp
CXX  <=  isv_app/operations.cpp
g++ isv_app/isv_enclave_u.o isv_app/isv_app.o isv_app/operations.o -o app -m64 -O0 -g -L/opt/intel/sgxsdk/lib64 -lsgx_urts -lsvm_u  -lsgx_ucv -L. -lsgx_ukey_exchange -lpthread -lservice_provider -Wl,-rpath=/home/test/PrivacyGuard-master/CEE/sample_libcrypto -Wl,-rpath=/home/test/PrivacyGuard-master/CEE -lsgx_uae_service
/usr/bin/ld: cannot find -lsvm_u
/usr/bin/ld: cannot find -lsgx_ucv
collect2: error: ld returned 1 exit status
Makefile:256: recipe for target 'app' failed
make: *** [app] Error 1

```

**Comment by jmp0x7c00** [comment]
and version of SGX SDK is 2.3.1 , rather than 2.0.1 in readme?
![图片](https://user-images.githubusercontent.com/16433413/166412356-99c0f3c2-4b55-4db0-aca7-ce1121fac07a.png)

**Comment by yang-sec** [comment]
Yes there should be a libsvm.a file in the repo but somehow it was not accepted to github. Can you comment out these two libs (and in related .cpp files) for the time being, and try the neural network (fann) option? 
I think we tried both versions in the experiment. v2.3.1 should work too.

**Comment by jmp0x7c00** [comment]
Yeah，it works，thanks very much！



发自我的iPhone


------------------ Original ------------------
From: Yang Xiao ***@***.***&gt;
Date: Tue,May 3,2022 10:27 PM
To: yang-sec/PrivacyGuard ***@***.***&gt;
Cc: jmp0x7c00 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [yang-sec/PrivacyGuard] build error,missing libs (Issue #6)





 
Yes there should be a libsvm.a file in the repo but somehow it was not accepted to github. Can you comment out these two libs (and in related .cpp files) for the time being, and try the neural network (fann) option?
 I think we tried both versions in the experiment. v2.3.1 should work too.
